apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/build-nudge-files: hack/nudging/container_digest.sh
    build.appstudio.openshift.io/repo: https://github.com/netobserv/netobserv-ebpf-agent?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    # switch comment in/out at branch cut / release
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-path-change: |
      [
        .tekton/**,
        Dockerfile.downstream,
        Dockerfile-args.downstream,
        .dockerignore,
        go.mod,
        go.sum,
        cmd/**,
        pkg/**,
        bpf/**,
        Makefile,
        LICENSE,
        vendor/**
      ]
    # pipelinesascode.tekton.dev/on-path-change: "[]"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: netobserv-ystream
    appstudio.openshift.io/component: netobserv-ebpf-agent-ystream
    pipelines.appstudio.openshift.io/type: build
  name: netobserv-ebpf-agent-ystream-on-push
  namespace: ocp-network-observab-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/ocp-network-observab-tenant/netobserv-ebpf-agent-ystream:{{revision}}
  - name: build-args-file
    value: Dockerfile-args.downstream
  - name: dockerfile
    value: Dockerfile.downstream
  pipelineRef:
    name: build-pipeline
  taskRunTemplate:
    serviceAccountName: build-pipeline-netobserv-ebpf-agent-ystream
status: {}
